# 配置文件

DAILY_TIME: "09:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-05-20" # 纪念日
CITY: "北京"
BIRTHDAY: "05-21"

APP_ID: "wx17856034961be653"
APP_SECRET: "232cf479dacf2d70d8d89a74467fd529"

USER_ID: 
  - "o-wQU6Q8uFa0mVwUR3feT0RCp0YM"
  # - "o-wQU6WpiVW0eUC-J_kKzBZa0-80"
  # - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "kkJwUxLasq-KR5x2QfkaLrFo8CPyH26obXr_xOxGaOY"